import rtconfig
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd, str(Dir('#'))]
src     = Split("""
main.c
sys.c
key_app.c
finsh_debug.c
displayInfo.c
delay.c
cpuusage.c
update.c
update_tcp.c
udp_server.c
../DSP_lib/arm_cortexM4lf_math.lib
""")

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
